throwErrorOnExtraParameters: true

templates:
    A4 portrait: !template
        reportTemplate: A4_Portrait.jrxml
        tableData: jrDataSource
        attributes:
            title: !string {}
            subtitle: !string {}
            datasource: !datasource
                attributes:
                    map: !map
                        maxDpi: 254
                        width: 555
                        height: 600
        processors:
          - !reportBuilder # compile all reports in current directory
            directory: '.'
          - !createDataSource
            processors:
              - !createMap {}
